### ISSUE TITLE
[Bug] Macros freeze up the board

### ISSUE THREAD

**Issue by MycroftHolmes1989** [OpenAnnePro/qmk_firmware#21]
## Describe the Bug
The keymap I am using is here: https://gist.github.com/MycroftHolmes1989/6535051ec74257b06dbc7be1ca50c875
Haven't made any changed in rules.mk.
The macros do not fire and makes the keyboard freeze.
I have tried with two Anne Pro 2 boards, both were C18 boards.

## System Information

 - Keyboard:  
   - Revision (if applicable):  Anne Pro 2 C18
 - Operating system: OpenSUSE as well as PopOS
 - AVR GCC version: 5.4.0

 - ARM GCC version: 9.2.1

 - QMK Firmware version: The master branch

 - Any keyboard related software installed?: 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ * ] Other: ObinsKit

**Comment by thomazmoura** [comment]
It might not be related, but try using AP2_SAFE_RANGE instead of SAFE_RANGE, since annepro2 defines some more keys using the SAFE_RANGE:

https://github.com/OpenAnnePro/qmk_firmware/blob/keyboard-annepro2/keyboards/annepro2/annepro2.h

When you hit any of those macros it will activate two different "key actions" since both custom codes are using the same range.

**Comment by MycroftHolmes1989** [comment]
That solved it. Thanks.
